### ISSUE TITLE
RFC for our optimization of libecc for secp256r1 ECDSA signature verification on a RISC-V VM

### ISSUE THREAD

**Issue by contrun** [libecc/libecc#3]
First of all, let me thank you for this great library. I learned quite a lot both as a software engineer and a cryptography newbie. The code quality and documentation of libecc are incredible.

I will give a overview of how we optimize libecc to a very specific use case. I'd like to hear your opinion on optimizing libecc on such a specific use. I am by no means a cryptographer or a performance expert. Our optimization are mainly driven by a practical demanding.

We at cryptape recently did [a few optimizations](https://github.com/cryptape/libecc/tree/riscv-optimized) (note that this is based on a old version of libecc, I did try to rebase it onto current master, but the code diverge too quickly to merge upstream changes) to libecc to a very specific use scenario. Our primary use case for libecc is to verify secp256r1 signatures on chain. As this signature verification will be ran repeatedly by every node with [a RISC-V ISA compatible VM](https://github.com/nervosnetwork/ckb-vm), its performance is critical to us. We decrease the cycles consumption of secp256r1 signature verification from 28M to 6M. The newest cycles consumption is much more acceptable to us.

Here is a summary of what we did.

- Using wNAF for point multiplication instead of double and add, https://github.com/cryptape/libecc/commit/7b3cf30169418de4c13539f7b15d6399f5a23101
- Using optimized assembly code for Montgomery multiplication, https://github.com/cryptape/libecc/commit/66ebda303c23b9e54971915c4d1f696a4a1b2f27#diff-d36e887cea500b3d6b8d98ffb3c736c0cb45c9302f3e0955cb3faa2f647c971d
- Replacing a few hot spot functions with compiler builtins or faster algorithms, e.g. using extended multiplication from gcc https://github.com/cryptape/libecc/commit/667d92e1de622e074f98e79b596be46833744ec4 , using a faster version of clz https://github.com/cryptape/libecc/pull/1/commits/ce95ac60032692ad370a27ed965a4d9bb6b44ded
- Cutting short in some originally constant time functions, especially code in `nn_cnd_{add,sub}`, `nn_cmp`, `nn_modinv` and `nn_iszero`
- Turning off a few checks in the critical path, most notably the checks in `{nn,fp}_init` and `{nn,fp}_check_initialized`

Our optimization may just be a mindless loop of profiling -> finding hot spot -> modifying code -> profiling. Did we miss the forest for the trees? Are there any well-known efficient algorithms that are worth to implement for faster signature verification? As a comparison, [the pure rust implementation of p256](https://github.com/RustCrypto/elliptic-curves/tree/master/p256) signature verification has a cycle consumption of 4.5M in ckb-vm (I haven't carefully studied this library yet, but it's amazing to see that a pure rust library has such a baseline), while bitcoin's secp256k1 with precomputed table (which is unfavorable in a constraint environment like ckb-vm) consumes only 0.9M in ckb-vm. What would you do if you're squeezing the performance of libecc to that level?

What are the changes we made nice to have them in upstream? Are non portable code changes non-acceptable even if there are gate-kept by compile-time flags? It this true for both compiler builtins and assembly code? Do you accept optimized non-constant time version of functions in the critical path? In our use case, we need only libecc's signature verification functionality. Timing attacks is irrelevant in this scenario. I previously [opened a PR](https://github.com/ANSSI-FR/libecc/pull/31) to make it easier for libecc to run on constrained environment. My reasoning to make a blanket random function is that randomness is irrelevant for signature verification. In the same vein, can we turn off some off the safety checks at the users' discretion, like checking nn/fp initialized? I do understand that cryptography library should be hard to misuse.

While optimizing libecc, I found the implementation of modular inverse and multi exponentiation are crucial to the performance of our use case. What algorithm besides wNAF would you choose to implement for multi exponentiation that is both efficient enough and easy to understand? Will you accept algorithms like [pornin/bingcd](https://github.com/pornin/bingcd) for better gcd performance?

I also found that `nn_set_wlen` is quite costly. Is it in general true that using fixed word length will result in worse performance? What are the other benefits of using flexible word length?

**Comment by rben-dev** [comment]
Hi @contrun,

Thanks a lot for all these feedbacks on libecc! Your work on dedicated RISC-V optimizations is quite impressive!
However, I find it difficult to integrate them in the upstream repo, and I will try to thoroughly explain why point by point:

1- Regarding low-level assembly optimizations or compiler builtins for algorithms such as Montgomery multiplication or binary gcd, the spirit of libecc is to be in pure `C` to avoid code complexity and simplify portability. This unfortunately removes many huge improvements on performance on dedicated platforms, but this is the price to pay. Other popular libraries such as OpenSSL or MbedTLS are more suited for specialized assembly code in order to squeeze the best of any platform. Compiler builtins are more portable as they do not depend on the platform, but they lack portability across compilers (and we want libecc to be compiled everywhere with a decent C compiler). On a side note, [pornin/bingcd](https://github.com/pornin/bingcd) seems to be only suited for 64-bit x86 with the BMI2 instruction set.

2- Regarding the fact that signature verification does not need to use countermeasures (contrary to signature), this is of course completely true but we have chosen to factorize the scalar multiplication code for both of them in order to simplify the code structure and the code auditability. This is arguable, but we feel that too much branches in the code structure (handling the various cases) make it difficult to keep track of the critical parts, and other libraries suffered CVE from too much complexity there. Also, some fault attacks countermeasures must be used for verification (only side-channels and some fault attacks are not concerned there). wNAF is a good technique to improve scalar multiplication, but using it for signature brings many challenges to avoid cache attacks and so on (meaning that we would have to maintain two versions of the scalar multiplication, with all the issues that come with this). Also, some more RAM is consumed for points precomputations, which can put pressure on very constrained devices.
The same previous reasoning holds for conditionally removing some sanity checks or cutting short in some constant time functions as you propose: too much code branches and `#ifdef` will increase complexity and hence decrease auditability (also, these checks allow to avoid fault attacks for both signature and verification, so we consider them as "important" in the core library). 

3- Regarding `nn_set_wlen` and the flexible word length, we have found that fixed length words has drastic negative impacts on performance for curves that are above 256 bits. For 521 bits curves leaving full length words can be catastrophic: this is why we have chosen to use the flexible size. For smaller curves (up to 256 bits), agreed that adapting the size might be more costly than leaving full words. But as a generic library (that should support many curves of various sizes), we feel that using flexible words is the most balanced way of dealing with the issue.

4- Regarding your question on how other libraries (such as the one in Rust) are able to achieve even better performance than your optimized libecc, my guess is that they use **dedicated arithmetic for P-256 curves** (see [P-256](https://csrc.nist.gov/csrc/media/events/workshop-on-elliptic-curve-cryptography-standards/documents/papers/session6-adalier-mehmet.pdf) section 4.3: the Generalized Mersenne Prime form of the primes of these curves allow for many simplifications of the modular arithmetic formulas, usually bringing a factor 5 to 10 or so in performance). You can refer to the same source for specific algorithmic optimizations of ECDSA on P256 curves to squeeze the most out of libecc for your use case. Since these are specific to P256, I am not very comfortable with introducing them in the code (following the same simplicity and portability spirit described above).

Finally, your point regarding blanket random functions for constrained environments where only verification is needed is interesting and as I commented in the PR, this is a challenging task because some countermeasures use randomness and "fake random" will break them. We can see what would be the best way to integrate this option without breaking the library.

Regards,

**Comment by contrun** [comment]
Hi @rben-dev ,

Glad to hear back. I think it is now quite clear that our code changes do not align well with the goal of libecc. We'll keep a fork to libecc for the moment. This issue can be closed. It may be of some use to people who wants to optimize libecc for their specific usage.
